# This file will be used to build for staging as:
#
#   jekyll build --config=_config.yml,_config_staging.yml
#
# You should change this to your own github account name
url: "https://tamouse.github.io"

## Your shouldn't change anything below this point!
baseurl: "/html-320-stylin-with-sass"
destination: docs/
