title: "Stylin' With Sass!"
baseurl: ""

author: Tamara Temple
description: Learn how to use Sass to make your CSS styles modular, extendable, and better prepared to fit into modern web site development.
keywords:
  - GDI
  - GDIMpls
  - Girl Develop It
  - Sass

# This is general info for GDIMpls
contact:
  name: GDI Minneapolis
  web: http://gdiminneapolis.com
  email: "minneapolis@girldevelopit.com"
  twitter: "gdimpls"
  github: "gdiminneapolis"

# There are a handful of styles available with reveal. They can be found in the
# reveal.js/css/themes folder, and include:
#
# style: gdicool
style: gdidefault
# style: gdilight
# style: gdisunny
# style: simple


# This is the directory the source files will be found in
source: source

# This is where your slides will be found, in the _slides/ folder.
# Number them in sequence
collections:
  - slides
  - oldslides

kramdown:
  input: GFM
  parse_block_html: true
