# You *MUST* change these two items:
title: Your Awesome Class
baseurl: "/jekyll-reveal-starter-kit"
# ^ This is the path of the slide set below the site URL.

# These are things you should customize for your class
author: Your Name
description: |
  Your awesome class in all it's glory.
keywords:
  - GDI
  - GDIMpls
  - Girl Develop It
  - Class
  - Awesome

# This is general info for GDIMpls
contact:
  name: GDI Minneapolis
  web: http://gdiminneapolis.com
  email: "minneapolis@girldevelopit.com"
  twitter: "gdimpls"
  github: "gdiminneapolis"


# There are a handful of styles available with reveal. They can be found in the
# reveal.js/css/themes folder, and include:
#
# style: gdicool
# style: gdidefault
# style: gdilight
# style: gdisunny
# style: simple
style: gdidefault

# Similarly, syntax highlighting styles are available in reveal. They can be found
# in the reveals.js/lib/ folder, and include:
#
# syntax_style: dark.css
# syntax_style: light.css
# syntax_style: zenburn.css
syntax_style: zenburn

# This is where your slides will be found, in the _slides/ folder.
# Number them in sequence
collections:
  - slides

exclude:
  - bin
  - CONTRIBUTOR_COVENANT.md
  - Description.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Outline.md
  - README.md
